### ISSUE TITLE
Layout of author names and newline in \addauthor

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#107]
One tester has found an issue with how names are wrapped:
![without](https://user-images.githubusercontent.com/14105363/218562935-557c8b15-7623-4e59-a092-e4793f31459b.png)
![emailwithout](https://user-images.githubusercontent.com/14105363/218563328-41ee4aa6-a2ad-481d-8601-ebab0ed136e7.png)

In order to correct this, the author inserted \\\ someplace, and found that it affected how emails are formatted because it inserted a newline into the author name.
![with](https://user-images.githubusercontent.com/14105363/218563067-9fca4c58-8700-43d4-a9f4-9392319e87bc.png)
![emailwith](https://user-images.githubusercontent.com/14105363/218563358-1033d294-a0ef-4888-8174-a37cca0a8d10.png)

In my opinion the cls file should properly typeset author names without breaking them in the middle. We should also forbid a newline inside \addauthor, but I'm not sure how to do that since \\ will have catcode 0.

This is related to how to handle [extremely long author lists](https://arxiv.org/abs/2210.03375) that may span more than one page. We should never break a name across a line or a page.

**Comment by kmccurley** [comment]
I think \maketitle should use \mbox to prevent author names from being broken across lines. Unfortunately I think \@maketitle needs to be extensively rewritten and documented better.

The check for commas in \addauthor is also incorrect. It still allows \addauthor{Kevin Doe, George Doe}. We should work harder to forbid these cases, while still allowing \addauthor{George Doe, Jr}. One way to do that is to forbid a command completely, but allow them to say \namesuffix{Jr} and we will insert the comma.

**Comment by jwbos** [comment]
I will take the issue of breaking author names: indeed mbox seems like a good solution or insertin "~" between the first and lastname. I will push a fix later this week. I will also investigate the checks in addauthor.

**Comment by jwbos** [comment]
We currently already issue a warning if a comma is used in addauthor. 
In [3258170](https://github.com/IACR/latex/pull/108/commits/3258170f51cdd2ece47d969198a439bfcc6bc3ab) I fixed the breaking of the author names and issue a warning if a newline is used in addauthor. 
Will think a bit about the \namesuffix before implementing.

**Comment by kmccurley** [comment]
I'm inclined to say that we should forbid ',' entirely in the \addauthor argument. I originally thought it might appear as "John Doe, Jr" but as it turns out the Chicago Manual of Style [recommends omitting commas](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Jr.Sr.III/faq0001.html). It is FAR more likely that people will use commas to write multiple names or Last, First than it is to separate a Jr (we've never had one in 25 years of eprint, for example). We don't want to accept those forms and I'd opt for a more restrictive move to prevent commas at all in a name.

I also think it's a lot easier to format the names as \mbox and use \begin{center} to wrap it all.

**Comment by jwbos** [comment]
Agreed, we now throw an error (see 6c6abc6).

**Comment by jwbos** [comment]
Reopening such that we don't forget to create some tests for this.

**Comment by jwbos** [comment]
Fixed in 29abcfff9c8b84710edb8b0dd5ae627e77fc53b3 and 685d1fd8215959c2f3b1ff1868423979657acb94.
