### ISSUE TITLE
Author footnote mark needs to be numeric

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#109]
I tried using
```
\addauthor[footnote={First footnote}]{Freddy First}                                                                                                                             
\addauthor[footnote={Second footnote}]{Susan Second}                                                                                                                            
\addauthor[footnote={Third footnote}]{Theodore Third}                                                                                                                           
\addauthor[footnote={Fourth footnote}]{Fredrick Fourth}                                                                                                                         
\addauthor[footnote={Fifth footnote}]{Freida Fifth}                                                                                                                             
```
and it gives an error `! LaTeX Error: Counter too large.` because these footnotes use footnote marks instead of numbers. This is a problem that we need to solve because papers with five authors are quite common. In the extreme case of [this paper](https://arxiv.org/abs/2210.03375) the authors gave up and manually encoded the footnotes using things like
```
\begin{small}                                                                                                                                                                   
  \begin{center}                                                                                                                                                          
    M.~Ablikim(麦迪娜)$^{1}$, M.~N.~Achasov$^{11,b}$, P.~Adlarson$^{70}$, M.~Albrecht$^{4}$, R.~Aliberti$^{31}$, 
```
with hardwired counters. That's because LaTeX classes typically don't handle that many footnotes. We need to do better.

There are two kinds of footnotes on authors:

1. affiliations, which use numeric footnotes that follow the author list.
2. per-author footnotes, which appear at the bottom of the page

Footnote numbering is currently numeric on affiliations, and a list of symbols on generic footnotes. The latter is the source of problems for the counter overflow, because it only allows a tiny number of symbols. I propose that we change those to something simple like  alphabetic [a-z] followed by aa-zz, etc. That way we wouldn't run out of symbols until we get to 26^2 authors.

In addition to the author footnotes and affiliation footnotes, someone might create a generic footnote for the paper, which has no number. They might *also* create an inline footnote in the text, and we should make sure that those are created with the limited number of symbols *, †, ‡, etc.

**Comment by jwbos** [comment]
Fixed in [c33e2de](https://github.com/IACR/latex/pull/110/commits/c33e2de9205230de84507a31fb704687415cbcfe).
