### ISSUE TITLE
test12, test13 and test14 fail on older python versions

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#115]
I was trying to trigger #112 on an ubuntu 20.04LTS machine which uses python 3.8. In the process I found that test7 works, but test12, test13, and test14 all fail in the part that extracts text from PDFs. PDFs are a godawful format, so extracting text has always been problematic. In this case the problem is that `pdfplumber` raises the exception:
```
AttributeError: 'LTChar' object has no attribute 'graphicstate'
```
I can think of two possible solutions:
1. don't run the tests on old systems
2. switch from pdfplumber to pypdf2. They both have failure modes, but pypdf2 seems to err on the side of simply giving up on the extraction of weird text.

**Comment by jwbos** [comment]
As discussed we care about tests passing for the Python + TexLive versions in the Docker.
