### ISSUE TITLE
We should prevent \begin{thebibliography} inline

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#116]
In compiling paper 125 from eurocrypt 2022, I noticed that the authors essentially bypassed the bibliography style by inserting \begin{thebibliography} into their main.tex file, essentially avoiding the use of the .bst file. We should prevent authors from doing this, since it completely bypasses the proper style and also avoids writing out citations in the metadata.

I'm not sure how to do this. We can save the `thebibliography` environment under some other name and only execute it if we think the bibliography was properly created from a file generated by bibtex and/or biber.

**Comment by jwbos** [comment]
Won't we catch this automatically when the .meta file is not generated?

**Comment by jwbos** [comment]
The .meta is generated even if `thebibliography` is manually inserted in the main.tex. 
We should try and detect this in a postprocessing step. 
I will see if we can do this in the docker when `version=final`.

**Comment by jwbos** [comment]
Exactly, I created a pull request for the runner which starts the Docker who attempts to detect this.

**Comment by kmccurley** [comment]
See line 99 in runner.py. I think this is fixed. Maybe needs a test.
