### ISSUE TITLE
footnotes for authors do not show up

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#122]
In my test where the list of authors spans two pages, the footnotes from authors do not appear. The error message is:
warning  (pdf backend): unreferenced destination with name 'Hfootnote.7' and it looks like:

![image](https://user-images.githubusercontent.com/14105363/221481426-1d1c0c3f-ef4f-4b9f-814f-9143612954b2.png)

I suspect this is because the footnote is not on the same page where the footnote is attached to the name.

**Comment by jwbos** [comment]
Does 40c80e4092ab51009f28c006d6f0034d60a3b4c5 fix this?

**Comment by kmccurley** [comment]
The lack of footnote was fixed, but now I noticed that there is no space after the footnote mark. See the footnotes for Eli Biham, where it has `w27,26` instead of `w,27,26`. This might be hard to fix, and I guess a space is sufficient.
![image](https://user-images.githubusercontent.com/14105363/221677990-db429667-5583-43b8-b71e-610354aff14b.png)

**Comment by jwbos** [comment]
Fixed in 147dfff22b2a28fcdf1893e463b9783e0151598a.
