### ISSUE TITLE
We need a plaintext option to \title

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#129]
I went through the papers from eurocrypt 2022 to see what people used in their titles, and it appears we need a `texttitle=` option on \title because people use all sorts of things that are not removed by \write:
```
\title{Stacking Sigmas: \\ \large A Framework}
\title{Batch-OT with Optimal Rate \index{Brakerski, Zvika}\index{Branco, Pedro}\index{D{\"o}ttling, Nico}\index{Pu, Sihang}}
\title{\titletext}
\title{A Greater \texttt{GIFT}:
Strengthening \texttt{GIFT} against Statistical Cryptanalysis}
\title{\bf A Complete Characterization of\\ Game-Theoretically Fair, Multi-Party Coin Toss\thanks{The author ordering is randomized}}
\title{Guaranteed Output in $O(\sqrt{n})$ Rounds\\ for Round-Robin Sampling Protocols\ifdefined\IsLLNCS\thanks{The full version of this paper is available at \url{https://eprint.iacr.org/2022/257}}\else\thanks{A preliminary version~\cite{conferenceversion} of this work appeared in \emph{EUROCRYPT 2022}.}\fi}
```
These produce all sorts of crap in the .meta file, including
```
\nobreakspace  {}\protect \cite {conferenceversion} of this work appeared in \protect \empy  {EUROCRYPT 2022}.
```
We shouldn't have to clean up this crap in the .meta file, so I propose to add a `texttitle` option and check the contents of title to see if it contains any macros.

We also need more tests to make sure that macros do not show up in the .meta title field. I'm quite sure that authors will produce crap here.

**Comment by kmccurley** [comment]
I'm having trouble using \ifnotstring because it only works when you pass #1 or #2 as an argument.

On the other hand I found a clever trick that allows us to iterate over the tokens in an argument so I can check 
```
\checkstring{this is just a string}          % does nothing
\checkstring{This has $a=b$ math in it}      % does nothing
\checkstring{This wraps
on the next line}                            % does nothing
\checkstring{this has a \textbf{macro} in it} % will raise a class error because it contains a macro
```
All I do is iterate over the tokens and raise an error if I encounter a token with catcode of \relax. This appears to be pretty close to what we want. Unfortunately it raises an error on `\"umlaut`. Authors can overcome this by using UTF-8 in their file.

**Comment by kmccurley** [comment]
I think figured out how to detect tokens that are accents, \%, \\, etc. Unfortunately it's kind of ugly. I step through the tokens `\tmp` and check if they are macros using `\ifcat`:
```
\ifcat\relax\noexpand\tmp
  % this means it's a macro
  \ifx\tmp\"     % detect an umlaut and do nothing
  \else
    \ifx\tmp\'   % detect an acute accent and do nothing.
       \else
         \ClassError{iacrcc}{Macros are not allowed in plaintext title}{}
        \if
    \fi
\fi
```
Unfortunately this results in a very deeply nested set of ifs for all of the single-character macros we would want to pass through. There are about 30 "Basic Control Sequences" listed in appending B that we could allow in plaintext arguments, because the python library will handle things like \"u and convert them to UTF-8.

I still have to figure out what to do with macros inside math mode, because there are potentially a lot of symbols that could be there. My preference is to allow things like \alpha to appear that way in math mode.

**Comment by jwbos** [comment]
I noticed that the plaintext option is **mandatory**: is that really what we want? If the title does not contain any macros why does the author need to specify this twice?

**Comment by jwbos** [comment]
Oops, this is already implemented in the current version. Plaintext is only mandatory when title contains a macro: my mistake.
