### ISSUE TITLE
Handle \thanks and \footnote in different places

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#133]
We have special handling of footnotes for title and author, but it's not completely clear to me what problem we are trying to solve. The \thanks macro is a special case of \footnote, It's not mentioned in the LaTeX companion, but in the LaTeX user guide it says that \thanks may be used in three places: \title, \author, and \date. There is a [writeup of the difference between \thanks and \footnote](https://tex.stackexchange.com/questions/289539/how-does-thanks-work-in-latex-article-class), and as far as I can tell it has to do with the choice of footnote mark and the width of the footnote mark.

My question is - what is our goal in defining our own footnote structures? Is it to control what footnote marks are used? Footnotes have various problems, such as the fact that \thanks does not work correctly in twocolumn mode, \footnote does not work correctly inside a minipage, inside \section, etc. Footnotes can also run on from one page to the next if they contain too much text (they can crowd out all text on the page).

I looked at how some Eurocrypt papers use thanks:
1. author ordering is randomized.
2. full version at ... \url
3. inside \author. This has weird behavior if you add that to your name in iacrdoc.tex, because I saw the same footnote twice then.
4. affiliations and email (we should disable \thanks and \footnote inside \addauthor).
5. an individual author says "Work done while visiting..."
6. acknowledging funding for a specific author. We need to give guidance in iacrdoc for how to handle these.
7. saying who the corresponding author(s) are.
8. some authors have all sorts of godawful \if through their latex to implement adherence to multiple cls files so they can resubmit someplace else. These people need to be beaten strongly about the head and shoulders.
9. the views expressed in this paper are those of the authors and do not necessarily reflect the official policy of ...

A lot of these uses are superseded by our \addauthor and \affiliation macros. Perhaps we should disable both \thanks and \footnote inside \addauthor and \title and \affiliation, but let's be clear on what problem we are trying to solve since the implementation of \footnote is pretty complicated. One thing is for sure - we need to prevent macros inside \addauthor and \affiliation, and \thanks are one thing we should expect authors to try and use.

I am attaching a txt file for bigf.tex which is a test case for \thanks and \footnote.
[bigf.txt](https://github.com/IACR/latex/files/11066670/bigf.txt)
[bigf.pdf](https://github.com/IACR/latex/files/11066668/bigf.pdf)

**Comment by jwbos** [comment]
The \thanks macro is indeed used in a variety of ways: your examples are indeed frequently used in the IACR venues. I would suggest to forbid the use \thanks (so we simply redefine \thanks just as we did for \author). My main argument is that the style file would like to control how the various footnotes look like and provide dedicated options for this. The \thanks macro is used for different purposes and we already provide alternatives for all (?) use-cases. Authors can specify if this paper is a full-version with \genericfootnote (or point (1), (2), (7), (9)). An author can acknowledge a person or a funding agency with the addauthor footnote option (or points (5), (6), (7)). 

Havin mutliple footnotes in a title (as in your example) should be disallowed (imo): I don't see any valid reason why we should allow this. Let's discuss in more detail in our next call.

**Comment by kmccurley** [comment]
One thing is not clear to me - why do we have footnote as an option to `\author`, but for generic footnotes, we use `\genericfootnote`. Wouldn't it be more consistent to add a `footnote` option to \title? The only difference is that you couldn't do multiple footnotes for a title, but at least it would allow context for the footnote on a title and would be more consistent with the other footnote construction

**Comment by kmccurley** [comment]
Another thought is that we haven't given much guidance about how to include text for funding. Shouldn't we have a `footnote` option for \addfunding? I can't think of a use case for `footnote` on an affiliation, so I'm less worried about that.

**Comment by jwbos** [comment]
Regarding `\genericfootnote`: this is a "generic" macro without marker to be used for the authors as they wish. This could be for a "full version" text, thank you / acknowledgement or funding information. If we do this as part of the title then we somehow signal it is related to the title (which is not necessarily true) and should this have a marker (or not)?

Text for funding is a more complicated issue. As discussed authors often need to include very specific phrases. Sometimes that relates to one and sometimes to multiple authors. Some people prefer to have this as a generic footnote on the first page while authors would like to have this in the acknowledgements. We could try and mold this into a consistent style but the easiest way (for the style and the authors using the style) is to let them write this.

**Comment by kmccurley** [comment]
I'm not sure how common it is, but [this paper](https://eprint.iacr.org/2023/060.pdf) has a shared footnote between two authors and I'm not sure this is possible in our structure. Perhaps they would use a generic footnote for this.

**Comment by kmccurley** [comment]
I believe what we agreed upon is the following:

1. we will disable \thanks and \footnote inside \title and \author.
2. the documentation will have clear guidance on how to add footnotes for authors and titles.
3. the documentation will have clear guidance about footnotes for funding (or use an acknowledgements section)
4. I'm not sure what to say about footnotes for affiliations. If an author wants to indicate a difference between current affiliation and affiliation during the work, then that should go into an author footnote (and the documentation will say this).

**Comment by jwbos** [comment]
Fixed in #147.

**Comment by kmccurley** [comment]
At the risk of flogging a dead horse, I'm still concerned about the desire to have shared footnotes between different authors. Here are two examples where a subset of authors share a footnote. In [this example](https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/642046f862fecd2a83761ff7/original/in-vivo-metabolic-imaging-of-1-13c-pyruvate-d3-hyperpolarized-by-reversible-exchange-with-parahydrogen.pdf) there are four authors sharing a footnote, and in [this example](https://arxiv.org/abs/2108.00049) there are two authors sharing a footnote.

I don't think this is a common construction in mathematics and Computer Science, but it's not unheard of either. Another thing I have realized is that the JATS format encodes footnotes with a [type](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/fn-type.html) that includes things like conflict of interest, a deceased author, current address, etc. Footnotes may be [associated with various entities](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/fn.html) including an affiliation, title, license, author, etc. This means that footnotes can be considered part of the metadata.

It's ok with me that iacrcc only encodes the relationships that we see are common in mathematics and computer science, because ultimately we are trying to balance being expressive enough with also being understandable to authors. We may have future requests to support something like additional footnote types. If so we could allow the `footnote` attribute on author to be a list, but that doesn't support shared footnotes. We could add something like `\sharedfootnote` and then refer to it from `\addauthor` with something like `sharedfn={1}` to refer to it by index. The most important thing seems like extensibility in the future, and the attribute model on `\addauthor` seems to allow that.

I intend to write something about this in the full version of the paper, but I think we should leave it out of the iacrcc.cls for now since it adds too much complication.

Feel free to close this again, but I wanted to record my thoughts here for the future.

**Comment by jwbos** [comment]
Fair point but I don't think we need this for CiC or in the IACR. CLosing for now until we get a specific request.
