### ISSUE TITLE
unbalanced \ifx in iacrcc.cls

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#135]
When we compile iacrdoc we now get the following in the log:
```
(\end occurred when \ifx on line 16 was incomplete)
```
The line 16 reference is from where iacrcc.cls is used so it isn't much help. I tried using `\tracingifs` but I couldn't understand the output. It makes it sound like there is an unclosed group within an ifx, but I don't know when this was introduced.

**Comment by jwbos** [comment]
Fixed in f2e0278. The error was in the line `\IfFileExists{luatex85.sty}{\RequirePackage{luatex85}}` where the trailing "{}" (for the false case) was missing.
