### ISSUE TITLE
\documentclass[draft]{iacrcc} disables license

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#140]
I noticed that some options to article just get passed straight through. If you add draft, then it messes up the doclicense text (though I'm not sure why). I don't know the definitive list of options but here are some I could find. Some are only enabled if you use LaTeX 2.09 \documentstyle instead of \documentclass, but the LaTeX user's guide lists them:

10pt, 11pt, 12pt, oneside, twoside, draft, final, titlepage, notitlepage, onecolumn, twocolumn, leqno, fleqn, openbib, a4paper (etc), landscape

We should disable any that cause conflicts.

**Comment by jwbos** [comment]
Do you have an example?
When I use  `\documentclass[draft,version=preprint]{iacrcc}` or `\documentclass[draft]{iacrcc}` I get

```
! Class iacrcc Error: Invalid options passed to iacrcc: draft.
See the iacrcc class documentation for explanation.
```

as expected.

**Comment by kmccurley** [comment]
I cannot recreate this problem, and I wish I had saved the example. Something had caused the license image at the lower right to not show up. I think I saw it only using latexmk -g -f -interaction=nonstopmode which forces it to continue running past errors. I'm closing this.
