### ISSUE TITLE
TU encoding not available under pdflatex

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#144]
Apparently I was wrong about using `\RequirePackage[TU,T1]{fontenc}` under pdflatex. It produces a warning:
```
Package fontenc Warning: TU encoding is only available with XeTeX and LuaTeX.
(fontenc)                Defaulting to T1 encoding.
```
This suggests that we should go back to your original `\RequirePackage[T1]{fontenc}` on line 169 of iacrcc.cls.

**Comment by jwbos** [comment]
Fixed in 69f17c99b9ecc757f05e2cb9be3a539ee46e1344.
