### ISSUE TITLE
inst has a bad design

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#148]
In talking to David Farmer from aimath.org, he pointed out that our design for capturing metadata could be improved in one place. Suppose a version of the paper has
```
\addauthor[inst={1}]{First author}
\addauthor[inst={2}]{Second author}
\affiliation[ror = 
\affiliation[ror=00za53h95,
             country={United States}]{Johns Hopkins University}
```
and then the first author adds an affiliation. In this case they have to **also** update the record for the second author, depending on where in the order of affiliations the new one is added. The relationship between `inst` and the ordering of affiliations is brittle and easily broken.

It would be better to use a key like bibtex entries to reference affiliations, with something like
```
\addauthor[inst={nxp, usc}]{First Author}
\addauthor[inst={mit}]{Second Author}
\affiliation[key=mit,
                country={United States}]{M.I.T.}
\affiliation[key=nxp,
                ror = 031v4g827,
                country={Belgium}]{NXP (Belgium)}
\affiliation[key=usc,
                ror        = 03taz7m60,
                country={United States}]{University of Southern California}
```
That way the `inst` value doesn't depend on the ordering of affiliations. The ordering of how affiliations are listed could be the order in which they appear in the paper, or the order they are cited in author order (I prefer the latter).

**Comment by jwbos** [comment]
I wouldn’t call this a bad design: this is simply how all style files (which I know) work. I have never heard a complaint about this before.
That does not mean this is a not sensible feature request: I will investigate how hard it is to implement this.

**Comment by jwbos** [comment]
Closing for now: this seems to be standard practice.
