### ISSUE TITLE
biblatex keys for Dutch names

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#173]
This is a very small issue, but biblatex is currently formatting citations incorrectly for some Dutch names. According to [this issue](https://github.com/moewew/biblatex-trad/issues/34) it is recommended to use `useprefix=true`. This is a tiny issue, but may arise in the future. Part of the question is how to sort names. It turns out that The Netherlands and Belgium differ on how to sort a last name like 'von Neumann', and Belgium libraries are slightly inconsistent ([see page 29](https://www.ifla.org/wp-content/uploads/2019/05/assets/cataloguing/pubs/names-of-persons_1996.pdf)). The alphaurl bibliography style seems to get it right, but we need the useprefix=true to get it right with biblatex.

**Comment by jwbos** [comment]
Let's discuss in our call tonight. I don't see the inconsistency but as a Dutch person living in Belgium I think we should be able to solve this ;-)
