### ISSUE TITLE
Some e-mail formats result in an error

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#178]
When using:

`\addauthor[inst=1,email={first.second_1@company.com}]{First Second}`

LaTeX will throw an error. The e-mail is converted to an url-link (which works fine) *and* also displayed (where the underscore causes the problem).

**Comment by jwbos** [comment]
Fixed in [40ee4ee](https://github.com/IACR/latex/pull/179/commits/40ee4eed11575c7b782fe0953ec4adb39c982013). Pull request created. 
Fixing using \noexpand\nolinkurl. \noexpand because hyperref is loaded last and using \nolinkurl from hyperref to fix this issue.

**Comment by kmccurley** [comment]
There are some other less-commonly used weird characters in email addresses, like <, % and ^, but hopefully those will never arise.

**Comment by jwbos** [comment]
These should work using \nolinkurl (but I haven't these).
