### ISSUE TITLE
cleveref must load after hyperref

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#183]
There are some packages that are eternally in a battle over who is loaded first. cleveref and hyperref are two of these. I found one paper#101 from crypto that uses cleveref, but it doesn't work with 

```
\usepackage[capitalize]{cleveref}
```
because it says cleveref has to be loaded after hyperref. We have \AtEndPreamble to insist that hyperref loads last. This was based on advice from the hyperref class, which is ridiculous on how many things it redefines in latex. As it turns out, cleveref disagrees with this advice.

My suggestion is that we put \RequirePackage{hyperref} at the end of iacrcc.cls, but let people load things in their preamble after hyperref. If things break, it's the problem of the author.

On another note, this is yet another reason to get rid of hyperxmp, because it also introduces problems in how it redefines some latex macros.

**Comment by jwbos** [comment]
I will dive into this: let's try and fix this once and for all. 
Some work has been done in this area: see https://ctan.mines-albi.fr/macros/latex/contrib/pkgloader/pkgloader.pdf I will investigate if this works fine (or not).

**Comment by jwbos** [comment]
One downside of pkgloader is that the following packages are required. Two standard expl3-related packages, one experimental package in l3regex and one user-contributed expl3 package in lt3graph.

**Comment by jwbos** [comment]
Never mind, it seems development of pkgloader was abandoned in 2018 and nobody is maintaining this: it has various issues with modern versions of LaTeX: a real shame.

**Comment by kmccurley** [comment]
Sounds like packageloader is not really viable - I'm skeptical of any further dependencies anyway. 

I think this might be really tricky because hyperref is so invasive and some authors have PDF/A requirements for their PDFs. See https://github.com/borisveytsman/acmart/issues/425 where problems with hyperref and hyperxmp came up.

The simplest solution seems like simply removing \AtEndPreamble surrounding \RequirePackage{hyperref}, and then make sure we load hyperxmp and hyperref in the correct order with the correct options. 

My inclination is to ignore problems in texlive that are prior to 2020, because we can always tell people to install a newer distribution of LaTeX.

**Comment by kmccurley** [comment]
I think the solution is to load `hyperxmp` first, because that's what the [section 2 of the current documentation](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/hyperxmp/hyperxmp.pdf) says to do. Then don't load `hyperref` in `\AtEndPreamble`, but use a simple `\RequirePackage` inside `iacrcc.cls`. I have a change to this effect, and I want to run the tests before sending you a pull request.

**Comment by kmccurley** [comment]
There is a related problem in texlive2023, namely that we set pdfauthor inside the abstract environment, and I think this is now too late. We need to separate the pdf stuff that is inside the abstract enviornment, and perhaps put it inside an `\AtBeginDocument` section. This is only slightly related to the current issue, but has to do when the order in which we cause things to happen. I only found this by running test11 on texlive2023. The pdfauthor is not set early enough for hyperxmp when it occurs in the abstract. It looks like hyperxmp generates the XMP package in \AtEndPreamble (I think), so we need to move the setting of pdfauthor to an earlier stage.

**Comment by jwbos** [comment]
> The simplest solution seems like simply removing \AtEndPreamble surrounding \RequirePackage{hyperref}, and then make sure we load hyperxmp and hyperref in the correct order with the correct options.

I am not convinved yet. What if the author needs to load a package *before* hyperref?

**Comment by kmccurley** [comment]
It appears that `longtable` is an example of something that needs to be loaded before `hyperref`. The problem of controlling load order is endemic in LaTeX, but it commonly associated with hyperref. There was one solution [mentioned here](https://tex.stackexchange.com/a/50860/274723) that looks for a file that contains packages that need to be loaded before hyperref. I think that's a feasible solution, but it only solves the problem by providing one earlier place to load packages. If we load A, B, C, D and the user wants to use a package that needs to be loaded after B but before C, then we would need to have a facility in the class file to load in each point between our `\RequirePackage{B}` and `\RequirePackage{C}`  lines. That seems ridiculous. 

This is a good example of why we should minimize our dependencies as much as possible. There are other examples where a package may have a complete conflict with something we are depending on (e.g., `afterpage` or `float`).

**Comment by jwbos** [comment]
FYI: see [github.com/mhelvens/latex-pkgloader/blob/master/pkgloader-recommended.sty](github.com/mhelvens/latex-pkgloader/blob/master/pkgloader-recommended.sty) for some entertaining rules in what order to load packages.

**Comment by jwbos** [comment]
Another approach is to introduce a class option `popular` or `common` which loads a batch of popular / commonly used packages (in the right order): this could include "problematic" packages such `varioref` / `cleverref` and could be extended over time.
