### ISSUE TITLE
Allow license with version=preprint?

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#187]
Someone may wish to include the license in their paper when they have preprint mode, but I'm not sure how critical this is. Alternatively we might have a footer on the title page that says "Preprint" or something like this in preprint mode.

It's relatively easy to do this by setting the footer for the titlepage (I already tried it).

**Comment by jwbos** [comment]
This has been fixed in 15e096abb58ec36eb407fc111efdd5901860cb6e
