### ISSUE TITLE
\title is required in preamble

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#192]
The following example illustrates a problem with our class.
```
\documentclass{iacrcc}
\addauthor{Fester Bestertester}
\begin{document}
\title{This is the title}
\maketitle
This is the content.
\end{document}
```
This generates the unclear error:
```
! Undefined control sequence.
<argument> \@plaintitle 
                        
l.3 \begin{document}
```
I had always assumed that `\title` would be used in the preamble, but apparently it is only required before `\maketitle`. In this case we don't define `\@plaintitle` before the `\begin{document}`.

One fix is to require `\title` to appear in the preamble.

**Comment by jwbos** [comment]
I will look into this.

**Comment by jwbos** [comment]
Fixed in [pull request](https://github.com/IACR/latex/commit/d7faf26e9a8b5cf0c699796db880afd2c004dd7d) https://github.com/IACR/latex/pull/194
