### ISSUE TITLE
Issue with meta data + utf8

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#198]
A bug was reported by that when a *second* (or later) author has "special" characters than the hyperxmp data is incorrect.

**Comment by jwbos** [comment]
After investigation this is indeed a bug in our style file when appending authors. Fix will be pushed soon.
I found another problem when special characters are used in the subtitle. This seems harder to fix...

**Comment by jwbos** [comment]
I failed to understand why subtitle does not work so I cheated and asked [stackexchange ](https://tex.stackexchange.com/questions/695525/pgfkeys-hyperxmp-utf8-problem/695537): this turns out to be another bug in hyperxmp. Yet another reason to migrate away from this package.

**Comment by kmccurley** [comment]
This is pretty ridiculous, but I don't understand why it handles pdftitle but not pdfsubtitle.

**Comment by jwbos** [comment]
Apparently hyperxmp converts the subtitle twice into utf8 which causes this bug.
Much simpler example is:

```
\hypersetup{pdfsubtitle=grüße}
\hypersetup{pdftitle=grüße}
```
where the title is shown correctly but subtitle not.

**Comment by jwbos** [comment]
Hyperxmp support has been removed in #203. 
Once the new `DocumentMetadata` work is integrated in the LaTeX kernel we will switch to this.
