### ISSUE TITLE
Final versions will compile when no affiliations are specified

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#209]

**Comment by jwbos** [comment]
Fixed in 15bb16e5cbddba7683745b7a4ac7cbcadf57ad8e

**Comment by kmccurley** [comment]
I'm skeptical that this is an actual bug. It's certainly unusual for people to lack an affiliation, but it's not unheard of. [Here is one](https://dl.acm.org/doi/abs/10.1145/2856693). Sometimes we make up bogus ones like "Independent Scholar", or "Digicrime" or "Self", but it seems unnecessary to make people declare an affiliation.

**Comment by jwbos** [comment]
I disagree. Currently, we have the requirement that for the **final** versions the affiliations need to provide a country. To me this implies that providing affiliations is mandatory. If we don't require affiliation it would also move away the IACR tradition from all our current publication venues. If indeed an author does not have an affiliation they can put "Self" or "Independent" as the affiliation.

**Comment by jwbos** [comment]
I just double-checked and the affiliation details (institution + country) are indeed mandatory as indicated by the screenshot from this Clarivate course I followed last year:
![CiC3 (002)](https://github.com/IACR/latex/assets/5672853/eb5afa3e-4fc6-4668-991a-bc49d1e7203e)

**Comment by kmccurley** [comment]
The vast majority of authors will specify an affiliation, and when they do that will require a country. The only reason why Clarivate asks for affiliations is so they can make sure the journal is international enough. That won't be a problem for us (everyone who has one would certainly list their affiliation, and then they need a country). Crossref doesn't care - they even allow anonymous publications. 🤡

I originally thought about asking for an ISO country code, but that's too annoying. Scopus is the other indexing agency that cares about country. They ask for JATS XML, which contains a country code on affiliation but luckily it seems to be [optional](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/country.html) in the schema. I'm using python `country_converter` to convert our country strings into a country code when I construct the JATS XML, but that will have some failure rate if people use non-standard names for countries.

**Comment by jwbos** [comment]
Providing an ISO country code (or not) is not the question here. 
When an author submits their final version for publication they simply should (imo) provide an affiliation as we require for all IACR publication venues.
