### ISSUE TITLE
We should check for natbib and forbid it

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#213]
The natbib package interferes with how bibliography styles work, and we should forbid it. At least one editor has [complained](https://tex.stackexchange.com/questions/379824/how-to-stop-natbib-from-modifying-bibliography-style) that natbib messes up Springer style. 

I found one paper (crypto 2023 #206) that uses natbib. In this case the author just wanted to use `\citet` to expand the author name prior to the reference. Thus, when the author enters `However, as observed by \citet{EC:HirZik10}` the result looks like

> However, as observed by Hirt and Zikas [58], 

I believe this is caused in part because Springer uses the widely-hated numeric style. The alphaurl style that we use would give `HK10`, which is at least a hint as to who the authors are. if the authors want to expand the names on a reference beyond this, then they can write it out in full or define their own `\citet` macro. Note that the authors don't even use natbib properly because [the documentation](https://mirror.math.princeton.edu/pub/CTAN/macros/latex/contrib/natbib/natbib.pdf) for natbib says to avoid using the standard `\cite` but authors mix it with `\citet` to occasionally expand the author names.

I looked at other papers uploaded for LNCS volumes and it appears to be fairly rare to use natbib (one paper each from Crypto 2023, Eurocrypt 2022, and Eurocrypt 2023). Nobody uses `\citep` but a few used `\citet`. All of these authors appear to mix `\cite` with `\citet` in spite of the instructions from natbib.

**Comment by kmccurley** [comment]
Perhaps we should reconsider this based on the fact that acmart supports it. We should discuss this together to evaluate the tradeoffs.

**Comment by jwbos** [comment]
Indeed, I first would like to understand the drawbacks and if this indeed changing the bibtex style.

**Comment by kmccurley** [comment]
After reading up about it, I think ACM supports so many different journals and conferences that they need to support multiple bibliographic styles. I don't think we need to support the numeric style at all, and that means natbib is pretty irrelevant.

**Comment by jwbos** [comment]
I started reading up on natbib as well and don't understand / see the benefits. I agree that we don't need to support this in our style.

**Comment by kmccurley** [comment]
I have a pull request to forbid loading natbib (along with a test).
