### ISSUE TITLE
Omit ISSN by default in header

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#216]
it appears that the timeline for obtaining an E-ISSN will be after the first papers are published, and presently the header has a default value shown.
![image](https://github.com/IACR/latex/assets/14105363/d2c358f9-16b4-4dbb-ae6e-69350e71d891)
I believe that we should do two things in `iacrcc.cls`:
1. set the default ISSN to empty.
2. if the ISSN is empty, then don't display the ISSN XXXX-YYYY at all. Start with "Vol ..." on that line instead.

**Comment by jwbos** [comment]
Fixed in #219.
