### ISSUE TITLE
consider implementing regex in cls file

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#237]
We have some authors forgetting to put `{}` or commas in their `\addauthor` macros, and the errors don't show up until they upload their paper (and the error message isn't very good because pydantic is where the regex matching occurs). There is apparently [a regex package](https://ctan.org/pkg/l3regex?lang=en) for LaTeX but I haven't tested it. Should we try to apply this to `orcid` and `ror` and `inst` and `email` during compilation time? It might catch things sooner, but writing regex is a real pain particularly for urls and email addresses.

**Comment by kmccurley** [comment]
This is an example of what the error message looks like in publish.iacr.org when the author forgets a comma after their `ror=`
![image](https://github.com/IACR/latex/assets/14105363/5959e740-c473-4c56-9691-5bffeef1b14a)
There are so many possible errors that can occur when parsing the `main.meta` file that it would be hard to catch just this one.

**Comment by jwbos** [comment]
I will investigate if we can use to catch some common mistakes early on.

**Comment by jwbos** [comment]
I had a closer look, the regexp package l3regex was merged into the LaTeX3 kernel: [l3kernel](https://ctan.org/pkg/l3kernel).
No need to load any additional packages. 
I made some basic tests for orcid, email and inst to catch basic mistakes.
This should provide some more useful error messages when people forget a comma.

**Comment by jwbos** [comment]
Merged with #238: this also fixes the Workflow test runs.
