### ISSUE TITLE
"Published" date is misleading

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#244]
In iacrcc.cls we insert a "Published" date in the footer, but this is inaccurate. In fact it's the time when the paper is compiled, but that could be off by weeks from the date when the paper is actually published. It's not really feasible to recompile all of the papers when the issue is published, and having an inaccurate "Published" date has all sorts of ramifications for patents and author credit and attribution. Having an incorrect date is unacceptable.

My suggestion is that we instead put the "Published" date into the HTML page, and do one of the following with the PDF:

1. change the string "Published" to "Produced" or "Compiled". I don't really like this option since I'm not sure what purpose it serves. The compilation date is embedded in the PDF as metadata under `/CreationDate` and `/ModDate` and these are visible to anyone who has access to PDF metadata. I don't see a need to display it in the footer.
2. eliminate the "Published" date altogether from the footer. I prefer this option.

**Comment by jwbos** [comment]
Agreed, this is only showed for final versions anyway. Option 2 makes the most sense.
See: Remove showing the published date on the PDF page. #245
