### ISSUE TITLE
Support for author control over bibliography labels

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#253]
I had previously been commenting on issue #252 about bibliography labels, but I decided that the discussion should really move to a standalone issue. When we set up iacrcc.cls, we originally chose alpha label style because we believed that it was preferred by most authors (and readers), and because it was consistent with iacrtrans. People can argue about which one is preferred, but it's easy to find both styles used in journals. I believe it was the right decision to choose alpha as the default, but the more I poke at this, the more I realize that alphabetic labels have a bunch of problems that authors can stumble into. For this reason, I'm leaning toward adding an option to switch to numeric labels [1], [2], ... I already have an easy PR to accomplish this.

It's not unprecedented to allow the author to choose their style, and I don't think we need to be insistent on one or another style. The default Springer class splncs04.bst uses numeric labels, but they allow authors to switch to alpha labels. Here is [an example](https://link.springer.com/chapter/10.1007/978-3-031-30545-0_6) from Eurocrypt 2023. Apparently American Mathematical Society also allows this ([section 10.3](https://www.ams.org/publications/authors/AMS-StyleGuide-online.pdf)). I looked at some papers from Proceedings of the AMS Series B and found some [numeric style](https://www.ams.org/journals/bproc/2024-11-12/S2330-1511-2024-00216-6/S2330-1511-2024-00216-6.pdf) and some [alpha style](https://www.ams.org/journals/bproc/2024-11-06/S2330-1511-2024-00208-7/S2330-1511-2024-00208-7.pdf). It's up to the author.

I can understand the desire to choose a standard style, but the only foolproof style is numeric and a lot of people hate it. That's why we chose alpha as a default. Unfortunately that style has a lot of corner cases that cause problems. In this bug I'll list a few of these problems with the alpha style in addition to the one that Dan mentioned.

1. if a `@misc` entry is missing an author (as it would for a website or a manual), then biblatex generates a completely empty label which looks ridiculous.
![image](https://github.com/IACR/latex/assets/14105363/d0526846-96b2-42ae-81ad-3088bec65808)
If you switch to using bibtex with `alphaurl`, then it generates the label from the year and gives something like
![image](https://github.com/IACR/latex/assets/14105363/0ff47d81-a253-4cc1-a432-05670b427b1d)
This is confusing because the `[20]` may not be the 20th reference in the list.
If there is no year, then it takes the cite key, which may be something not intended to be shown to the reader. If the cite key is `@misc{evidence,`, then the label comes out as `[evi]`.

2. we allow authors to use either bibtex with the alphaurl style, or else biblatex with the alphabetic style. These look similar, but they're actually different and they result in different sort orders. Here are some examples of the differences from [a CiC paper](https://cic.iacr.org//p/1/1/2)
```
bibtex       biblatex
AHIV23    Ame+23
BCC+16   Boo+16
BSCI+23  Ben+23
```
3. alpha labels don't sort by author order - it sorts by key order. Hence we end up with strange author orderings like this:
![image](https://github.com/IACR/latex/assets/14105363/11d64dce-077b-4558-b03a-1f4a84fc5765)
This can interfere with finding a reference when it appears in a place you don't expect it.
4. alpha style doesn't properly handle hyphenated last names.
5. it can generate embarrassing labels like `BS01`, `Bad14`, and `ASS15` (all of these are generated from cryptobib). 

As it turns out, authors who use biblatex can completely override the bibliography labels. In some cases, they can do it on an entry-by-entry level using `label={foobar}` in their bibtex entry. In this case it would generate `[foobar08]` if there is no author and the year is 2008. 

Authors can also completely override the formatting of the label using something like
```
\DeclareLabelalphaTemplate{                                                                                                      
  \labelelement{\field[strwidth=1, strside=left, lowercase, names=3]{labelname}}                                                 
  \labelelement{\literal{@}}                                                                                                     
  \labelelement{\field[strwidth=2, strside=right]{year}}                                                                         
}
```
to get completely ugly custom formatting like
![image](https://github.com/IACR/latex/assets/14105363/3066de8f-ca68-440f-a638-086c2a79e7e1)
I shudder to think what happens when people realize they can use UTF-8 emojis in the labels. 
![image](https://github.com/IACR/latex/assets/14105363/6f4c2ce8-5537-436a-9c20-c2fe3631be81)

In almost every case I think the default alpha labels are better, but there are enough weird failure cases that I think it makes sense to allow authors to opt for numeric labels instead of pursuing the biblatex trickery that is possible.

**Comment by ahuelsing** [comment]
I generally prefer the alpha labels as a reader as they help me to easier re-recognize a reference while reading a paper. However, I fully agree that biblatex introduces bias that is unacceptable. Is there a reason why we need to allow biblatex instead of just doing bibtex?

**Comment by jwbos** [comment]
I have no objection against adding technical support in the LaTeX class for numerical references. However, what is allowed to be used in a journal is a decision by the EiCs who strive for an unified look and feel. Hence, modifying this look and feel with biblatex is not allowed (although possible).

**Comment by kmccurley** [comment]
After our discussion today, it's more clear what is desired, namely that we should use alphabetic labels but `biblatex` and `bibtex` should produce essentially the same output. We would also like authors to avoid customizing the labels unless it is obviously necessary.

One approach to this is to use `style=trad-alpha` in `biblatex` instead of `style=alphabetic`. This uses a feature of the [trad-biblatex](https://ctan.math.washington.edu/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-trad/biblatex-trad.pdf) package. That package _attempts_ to produce the same thing as the `alpha` style in `bibtex`, but unfortunately it fails in some cases.

Note that authors can influence how the label is constructed using either the `key` field in `bibtex` or the `label` field in `biblatex`. There are some `key` values for `@Misc` entries in `cryptobib`. `biblatex` also has the `shorthand` field that overrides the label.

**Comment by kmccurley** [comment]
The editors have decided that the alpha style should be used on all papers.
