### ISSUE TITLE
changes package incompatibility

### ISSUE THREAD

**Issue by Honzaik** [IACR/latex#257]
Hello,

I noticed that the changes package (https://ctan.org/pkg/changes?lang=en) seems to not work with the template.

If I use the provided `template.tex` and add`\usepackage[commandnameprefix=ifneeded]{changes}` (after `\documentclass{iacrcc}`) there are no errors, but when I try to use the package commands (for example in the introduction section) the text inside the commands doesn't render (`\added{}`, `\deleted{}` etc.)

I also attempted to use the `after-hyperref.sty` method described in the template documentation but that didn't seem to help. 

I understand that supporting every package is impossible but this one may be useful for revisions (I guess as an alternative to latexdiff). Unfortunately, I am not skilled enough in tex so I cannot pinpoint the issue/submit a patch myself.

Cheers

**Comment by kmccurley** [comment]
I can confirm that the package does not seem to work, but I am unable to understand why. The `changes` package loads a bunch of other things including `ulem` and `truncate`, but I don't see any conflict in those. I tried it in `after-hyperref.sty` to load it later and it didn't seem to make any difference. I get different kinds of errors depending on how I load it. If I use
```
\usepackage{changes}
```
will trigger an error that 
```
! Package changes Error: Command comment is already defined..
```
This leads me to think that the `changes` package has a lot of conflicts with other things. My home machine has texlive2023 installed, so it's hard to update that. The docker image is also running texlive2023, but perhaps we should try using texlive2024. overleaf just made texlive2024 available yesterday.

**Comment by Honzaik** [comment]
I forgot to mention the distro details. I tested it on my machine which has texlive2024 + it also doesnt seem to work on Overleaf's 2022, 2023 and 2024 version. 

I noticed that the error which shows up when using `after-hyperref.sty` is the same that shows up when the parameter `commandnameprefix=ifneeded` (which tries to resolve conflicts) is omitted. But I dont know if it helps with identifying the issue.

**Comment by jwbos** [comment]
I only see this issue now. I will have a look tonight and check what is going on. Thanks for reporting!

**Comment by jwbos** [comment]
This was an interesting one. I misunderstood how the `\noexpandarg` macro (from the[ xstring package ](https://ctan.org/pkg/xstring?lang=en)) exactly works. This influenced the behavior of the `changes` package. 
This has been fixed. 

I found another problem between the `changes` and the `doclicense `package. When both are loaded (order does not matter) then one gets an incomplete PDF (no error messages). I haven't found a solution but best to simply not call the `\license` macro when using `changes`. 

See 7240688146609f870e809326f6fd039e5d5f2eda for the fix.

**Comment by kmccurley** [comment]
Since final versions require a `\license` to be set, does that mean they need to comment out `\usepackage{changes}` when they upload their final version?

**Comment by jwbos** [comment]
Indeed, for the final version the `changes `package cannot be used (but I don't see why one would need this).

**Comment by jwbos** [comment]
Correction: one can use `changes` and `doclicense` together. 
One has to use the `\chcomment` command, as `\comment` is defined by the `verbatim` package (loaded by `doclicense`).
(As explained in the documentation of `changes`.)
So this resolved the issue completely.
