### ISSUE TITLE
We should check subtitle for illegal macros

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#265]
The `subtitle` attribute of the `\title` macro is written to metadata, and therefore it should not contain user-defined macros. At the present time we do not check this. The title itself is allowed to contain math and accents, but not macros. We should apply the same check to subtitle. Otherwise the subtitle may not be meaningful in the captured metadata since it could contain something like `\protect \LaTeX  \`
if the original subtitle contains the macro `\LaTeX`. This is but one example.

**Comment by jwbos** [comment]
Fixed in 37575cb.
