### ISSUE TITLE
Add checks in \AtEndDocument

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#73]
We depend heavily on our macros not being redefined. If a paper used \renewcommand{\title} then we would lose the ability to capture the title in the metadata. Some packages like unicodemath even delay their definitions until \AtBeginDocument so that they can override anyone else's. It's not possible for a macro to guarantee that it cannot be redefined, but we can check \AtEndDocument to see if the macro was changed. If so, then we would generate a ClassError to tell the author not to modify the macro. See [this comment](https://tex.stackexchange.com/questions/12362/test-if-a-command-has-been-defined-by-another-package/12379#12379) for how to do it.

Note that the [letltxmacro](https://mirror.mwt.me/ctan/macros/latex/contrib/letltxmacro/letltxmacro.pdf) package allows authors to temporarily override commands, so that is one way authors could still screw up the metadata.

**Comment by kmccurley** [comment]
Reopening this because I found out there is a new command \NewCommandCopy that works better than \let to save a copy of a command. Apparently \let does not work for commands with optional arguments or robust commands. We may want to switch to using this in iacrcc.cls.

**Comment by jwbos** [comment]
I worked a bit on this but as everything in LaTeX this is complicated. \ifx does not succesfully compare commands declared with \NewCommandCopy: any idea how we can compare the two macros?
