### ISSUE TITLE
We don't need page numbers

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#79]
The iacrtrans.cls has stuff in it with page numbers. These are a legacy holdover that some publishers think they need in order to identify where to find a paper in a bound issue of the journal. In the case of ToSC and TCHES, they actually include the page numbers in the DOI, but this only introduces unnecessary dependencies. For an electronic-only journal, page numbers are irrelevant - the only thing that is required to cite an electronic journal is the DOI. Some journals are additionally adding "article numbers" but these have no corresponding bibtex field so I think they are extraneous. The DOI is all we need. None of the traditional citation guides insist on page numbers any more. The [APA style guide](https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references#1) now says "If the journal does not use volume, issue, and/or article or page numbers, omit the missing element(s) from the reference." The latest MLA reference also says page numbers are optional.

This shows up in several places:
1. in a bibtex entry for a paper in this journal, the pages field may list the total number of pages in the article rather than a page range. If someone insists they would put pages={1-25} if the paper has 25 pages. The pages field is optional in @inproceedings and @article anyway. When we export BibTeX for these papers, we should include a page range like 1-25.
2. when someone cites the paper, they may wish to refer to a part of the document. For example someone may use [5, pp 23] to indicate the material they are referring to is on page 23. Since our papers will have page numbers in them (starting at 1), this is still valid.

**Comment by kmccurley** [comment]
@ahuelsing raised this issue in our call today. I should mention that the current practice of tosc and tches is to include a range of page numbers in the DOI, but this explicitly [violates the best practices statement](https://www.crossref.org/documentation/member-setup/constructing-your-dois/) from crossref that DOIs should be an opaque identifier that does not include visible metadata. See [this discussion](https://community.crossref.org/t/crossmark-change-one-doi-overlapping-the-pages-of-another-article-with-a-different-doi/3525/2) in the crossref community forum where they mention page numbers as a problem. There is never a need for papers to be assigned a range of page numbers that do not overlap another paper. The requirement for non-overlapping page numbers is an archaic requirement that predates the existence of DOIs. For journals that do not have a print edition, they are no longer used. We will assign page numbers of the form 1-x, but other papers in the issue will also be assigned page numbers of 1-y. The identifier for a paper does not involve the page numbers - it's the DOI. All bibtex entries for a paper should include that DOI.

There is now a tracking issue in IACR/latex-submit to handle page numbers.

**Comment by kmccurley** [comment]
I'm reopening this because the style puts page numbers in the header. 
![image](https://github.com/IACR/latex/assets/14105363/d0d8f25c-c19c-4bd1-8a0f-3a03cb1917b4)
The problem with this example is that page numbers have been used as part of a citation to distinguish papers from one another, but we might have two papers with the exact same page numbers 1-30. I would prefer that we either eliminate this or change it to say "30 pages" so that it doesn't look anything like a page range. Otherwise we encourage people to use the old style of citation with page numbers, which could be misleading.

**Comment by jwbos** [comment]
I don't understand the problem exactly: one can simply distinguish the paper by the title, right? (Even if they have the same page count and are published in the same Volume). How does changing from page range to page count fix this?

**Comment by kmccurley** [comment]
the problem is that it says pp 1-8, as if those are the page numbers within the issue. The issues don't have page numbers, so to say that it's pages 1-8 is misleading. My fear is that people will start citing things with pages={1--8} in bibtex as if that is part of the identifying information for the paper. Then when they get ingested into citation databases like DBLP or crossref, it will cause conflicts because papers in the same issue have overlapping page ranges. It would be better to have no page ranges at all.

**Comment by kmccurley** [comment]
Here's another way of thinking about it: what value is conveyed by having `pp. 1-28` in the header? If they have the PDF, then they can see the number of pages in the file. That header is present on `iacrtrans` because they actually assign unique page ranges, whereas we don't intend to.

**Comment by jwbos** [comment]
Fixed in #220.

**Comment by kmccurley** [comment]
There is some doubt about what a bibtex entry should look like for a paper that is published with an article number instead of a page range. In the original design of bibtex, everything was on paper and you needed the page range to find the paper. The `pages` field in `@article` and `@inproceedings` is optional, but it was easy to figure out what goes there (the field is used for the number of pages in case of `@book`). When a paper is published with an article number rather than a page range, it's not clear how to put that into bibtex ([there is no standard](https://tex.stackexchange.com/questions/445888/best-practice-for-bibtex-entries-with-paper-number-rather-than-page-number)). IEEE Transactions uses a `paper` field, but nobody else does. [`biblatex](https://ctan.math.illinois.edu/macros/latex/contrib/biblatex/doc/biblatex.pdf)` has both `eid` and `number` and they suggest using `eid` (but it's not clear if this is globally unique or only unique within an issue).
There are really two issues:
1. how to structure the bibtex database entry
2. how a bibtex style should display it.
BibTeX is a festering mess that is still mired in the 80s.
