### ISSUE TITLE
Provide PDF/A compliance

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#89]
This a long term problem with no immediate solution. I mention it here because we should return to it in a year when the LaTeX project comes up with a better solution. For now I think our best solution is to switch from hyperxmp to pdfx. I have a version of iacrcc.cls that uses pdfx and it produces fewer errors under verapdf.

Some publishers and funding agencies are trying to demand PDF/A versions of papers. This is quite a mess in LaTeX. One requirement for PDF/A is XMP metadata, but that is not enough; there are still other problems with producing PDF/A compliant documents from LaTeX:

1. there is apparently no support for PDF/A color spaces. Any included graphics can trigger a problem.
2. the CC-by logo apparently has transparency, which is forbidden for PDF/A.
3. there is a requirement for the PDF /Info dictionary to agree with the XMP metadata if it exists. Unfortunately the correct way to provide XMP data for multiple authors is to list them in an RDF list, but there is no way to put such a list into the info dictionary. Many validators will complain about this. This is mentioned in the documentation for hyperxmp. One solution is to omit the info dictionary and rely only upon XMP. The info dictionary is actually deprecated in PDF 2.0 anyway.
4. fonts need to be embedded into the document. Since authors are free to use weird fonts, this can be a problem.

There are a bunch of half-hearted efforts to provide PDF/A compliance in LaTeX, including pdfx and hyperxmp. Neither one addresses the problems mentioned above. There is a [project within latex3](https://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/pdfmanagement-testphase/pdfmanagement-testphase.pdf) to address these problems but it's not yet finished. None of pdfx, hyperxmp, or xmpincl are compatible with this.

The acmart class has punted on this issue; we should do the same for now but return to it in years to come.

**Comment by thomwiggers** [comment]
Some of these problems are dependent on the level of PDF/A chosen: for example, transparency is allowed in PDF/A-2. I found it hard to generate compliant, non-trivial documents though.

**Comment by thomwiggers** [comment]
Agreed, I tried getting as far as I could in my PhD thesis, but I eventually called it a day.

**Comment by kmccurley** [comment]
This relates to PR #203 and the iacrdoc.pdf that was checked in. The a-2u profile seems like a viable choice. I ran some validation tests and got inconsistent results: 
1. verapdf 1.24 says that it passed
2. pdfen.com it failed saying that the "documents metadata was either missing or inconsistent or corrupt". This is so vague as to be useless. 
3. avepdf.com it failed saying that "XMP property xmpRights:WebStatement not defined in current schema." I believe that is incorrect because the schema is http://ns.adobe.com/xap/1.0/rights/ and [part of the XMP standard](https://developer.adobe.com/xmp/docs/XMPNamespaces/xmpRights/).
4. https://www.pdf-online.com/osa/validate.aspx says that it fails. the message is: The 

> Unicode for cid 87 is unknown.
> The document does not conform to the requested standard.
> The document contains fonts without appropriate character to unicode mapping information (ToUnicode maps).
> The document does not conform to the PDF/A-2u standard.
5. https://www.pdfforge.org/online/en/validate-pdfa says that it's a valid PDF/A-2u file.
6. apache pdfbox prefllight gives the following errors:

> 1.4 : Trailer Syntax error, /XRef cross reference streams are not allowed
2.2.1 : Invalid graphics transparency, Group has a transparency S entry or the S entry is null [COSDictionary{COSName{Length}:COSInt{2013};COSName{Type}:COSName{XObject};COSName{Subtype}:COSName{Form};COSName{FormType}:COSInt{1};COSName{PTEX.FileName}:COSString{/usr/local/texlive/2023/texmf-dist/tex/latex/doclicense/images/doclicense-CC-by-88x31.pdf};COSName{PTEX.PageNumber}:1;COSName{PTEX.InfoDict}:COSOb on page 1
2.2.1 : Invalid graphics transparency, Group has a transparency S entry or the S entry is null on page 1
7.1.1 : Error on MetaData, No type defined for {http://www.aiim.org/pdfa/ns/id/}year
7. https://www.pdf2go.com/validate-pdfa says that it passes PDF/A-2u.
8. https://xodo.com/validate-pdfa says that it fails, with these errors:
> Embedded Type1 font program does not define all font glyphs
A description for a property is missing in 'pdfaSchema:property' sequence
Some text can't be mapped to Unicode
9. https://online.visual-paradigm.com/online-pdf-editor/pdfa-validator/ says that it passes PDF/A-2u.

I do not have access to Adobe Reader Professional. 

The inconsistency of these tools suggests to me that PDF/A is a poorly defined standard.

**Comment by thomwiggers** [comment]
I generated the following PDF/A-2u compliance report using Adobe Acrobat.

[iacrdoc_report.pdf](https://github.com/IACR/latex/files/12607379/iacrdoc_report.pdf)

The problem appears to be the FontAwesome glyphs, which do not map to unicode characters.

**Comment by kmccurley** [comment]
Thanks for this! In retrospect this is not surprising, since `fontawesome` is a custom font that doesn't map to UTF-8. 

I can see two possible solutions to this problem:

1. The U in PDF/A-2U specifically refers to the unicode requirement. One benefit of the 2U profile is that text can be copied from the document and it is possible to extract text for indexing. These seem like important features. We could downgrade to using PFD/A-2b using `\DocumentMetadata{pdfstandard=a-2b,pdfversion=1.7}`. This seems like a step back, since I like the fact that text could be copied from the PDF - this is an issue that comes up in eprint when people copy from their abstract and end up with ligatures that don't correspond to UTF-8 characters.
2. we can completely remove the dependency of iacrcc.cls on `fontawesome`. It turns out we only use it for the external link symbol of a square with an arrow inside. This has no comparable UTF-8 glyph (See [this issue](https://gist.github.com/miguelmota/322c89234d60de578f37d3c6d30f7e41) where they grapple with the same problem). We are already using a tikz image for the ORCID icon, and we can similarly switch to a tikz image for the external link icon. This would remove our dependency on `fontawesome`. 

I prefer option 2, in part because we should reduce the dependencies of iacrcc.cls to the bare minimum. I have a pull request that implements this and I'll send it for review. As part of the review, we should check if the resulting iacrdoc.pdf passes the adobe PDF/A-2U check on Adobe Reader Pro. The output looks like this (the blue can be easily changed to the hyperref link color).
![image](https://github.com/IACR/latex/assets/14105363/acbe0f65-3bc0-4aff-824f-9d20a11e12c4)
[iacrdoc.pdf](https://github.com/IACR/latex/files/12614280/iacrdoc.pdf)

Note that there are lots of ways that an author could screw up PDF/A compliance in their LaTeX (e.g., using fontawesome or graphics with transparency or strange color profiles). That's not really our concern - we just don't want iacrcc.cls to impose any requirement that would interfere with PDF/A. 

As a side note, it's possible that we could incorporate PDF/A validation as part of publish.iacr.org, by installing verapdf on the docker container and running it. verapdf can easily produce an XML output that we can transform into our format to display to authors, but I am somewhat distrustful of verapdf.

**Comment by thomwiggers** [comment]
For reference, this is the Acrobat compliance report for the `iacrdoc.pdf` that was uploaded in Kevin's latest comment [iacrdoc-2_report.pdf](https://github.com/IACR/latex/files/12673953/iacrdoc-2_report.pdf)

**Comment by jwbos** [comment]
Thanks! Good to get other confirmations, I am checking mainly with veraPDF.

**Comment by kmccurley** [comment]
Thanks Thom! I'm going to close this now, though we might need tests in the future to make sure that we preserve PDF/A-2u on iacrdoc at least.
